name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - name: Windows
          tag: windows-latest
        - name: Ubuntu
          tag: ubuntu-latest
    name: Unit Tests (${{ matrix.os.name }})
    if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ${{ matrix.os.tag }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin # Eclipse Temurin
        java-version: '11'    # Java 11 (LTS)
        cache: 'maven'
    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v4
    - name: Run Tests
      run: |
        mvn test
    - name: Publish Test Results
      if: ${{ always() }}
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: "**/TEST-*.xml"
        exclude_sources: target/
        check_name: Test Results - ${{ matrix.os.name }}
